version: 2.0

jobs:
  prepare:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - .
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum ".circle-sha" }}
            - v1-bundle-{{ .Branch }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: v1-bundle-{{ .Branch }}
          paths:
            - vendor/bundle

  style:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-{{ .Branch }}
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake style

  specs:
    docker:
      - image: circleci/ruby:2.3.4
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-{{ .Branch }}
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake spec

workflows:
  version: 2
  build:
    jobs:
      - prepare
      - style:
          requires:
            - prepare
      - specs:
          requires:
            - prepare
